[build]
builder = "heroku/buildpacks:20"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t src/frontend/assets/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
PHP_VERSION = "8.1"

[variables]
APP_ENV = "production"
